# VirtualEnvironment
 Testing first package


 Use 
 $ python -m pytest

====ERROR=============================================================================
ERROR collecting Lib/site-packages/astroid/test_utils.py 
imported module 'astroid.test_utils' has this __file__ attribute:
  C:\Users\info\AppData\Roaming\Python\Python37\site-packages\astroid\test_utils.py
which is not the same as the test file we want to collect:
  C:\HomeProjects\VirtualEnvironment\Lib\site-packages\astroid\test_utils.py
HINT: remove __pycache__ / .pyc files and/or use a unique basename for your test file modules

FIX: create a pytest.ini file in the root of the project
======================================================================================

====ERRORS============================================================================
  C:\Users\info\AppData\Local\Programs\Python\Python37\lib\site-packages\_pytest\mark\structures.py:324: PytestUnknownMarkWarning: 
Unknown pytest.mark.acceptance - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

FIX: 
======================================================================================

